name: Pyre

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pyre:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code into the runner
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      # Run Pyre Action
      - name: Run Pyre Action
        uses: facebook/pyre-action@main  # Update with the desired version or branch
        with:
          repo-directory: './'
          requirements-path: 'requirements.txt'
